apiVersion: v1
kind: Service
metadata:
  name: {{ include "adot-fargate.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adot-fargate.labels" . | nindent 4 }}
    app: aws-adot
    component: adot-collector-config
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
  selector:
    {{- include "adot-fargate.selectorLabels" . | nindent 4 }}