clusterName: "" # [REQUIRED]
region: ""      # [REQUIRED]

replicaCount: 1

image:
  repository: amazon/aws-otel-collector
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "adot-collector"

podAnnotations: {}

podSecurityContext:
  fsGroup: 65534

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8888

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 400Mi

nodeSelector: {}

tolerations: []

affinity: {}
